In [4]:
import pandas as pd
series=pd.Series([1,20,30,40,50],index=['a','b','c','d','e'])

In [5]:
series

a     1
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
series['a':'c']

a     1
b    20
c    30
dtype: int64

In [8]:
import pandas as pd
series=pd.Series([1,20,30,40,50])
print(series)

0     1
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
series[1:3]

1    20
2    30
dtype: int64

In [2]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)
pd.set_option("display.float_format","{:.2f}".format)

In [13]:
data=pd.read_csv(r"C:\Users\asing\Downloads\sales_data.csv")

In [14]:
data

       Name Product Name  Sale Price    MRP  Rating   Sale Date
0     Alice     Product1      100.00 120.00    4.50  01-08-2023
1       Bob     Product2      150.00 170.00    4.00  02-08-2023
2   Charlie          NaN      200.00    NaN    3.50  03-08-2023
3     David     Product4         NaN 210.00    5.00  04-08-2023
4       Eva     Product5      250.00 270.00     NaN  05-08-2023
5     Frank          NaN      300.00 320.00    4.70         NaN
6     Grace     Product7      350.00    NaN    4.10  07-08-2023
7     Helen     Product8         NaN 370.00    3.80  08-08-2023
8       Ivy     Product9      400.00 420.00     NaN         NaN
9      Jack          NaN      450.00    NaN    4.30  10-08-2023
10     Kara    Product11      500.00 520.00    4.90  11-08-2023
11      Leo    Product12         NaN 570.00     NaN         NaN
12     Mona    Product13      550.00    NaN    3.90  13-08-2023
13     Nina    Product14      600.00 620.00    4.60  14-08-2023
14    Oscar          NaN      650.00 670.00    4.20  15-08-2023

In [12]:
data.head()

     Name Product Name  Sale Price    MRP  Rating   Sale Date
0   Alice     Product1      100.00 120.00    4.50  01-08-2023
1     Bob     Product2      150.00 170.00    4.00  02-08-2023
10   Kara    Product11      500.00 520.00    4.90  11-08-2023
13   Nina    Product14      600.00 620.00    4.60  14-08-2023

In [7]:
data.tail(2)

     Name Product Name  Sale Price    MRP  Rating   Sale Date
13   Nina    Product14      600.00 620.00    4.60  14-08-2023
14  Oscar          NaN      650.00 670.00    4.20  15-08-2023

In [32]:
import numpy as np
import pandas as pd
arr=np.random.randint(10,20,(3,3))

In [33]:
data1=pd.DataFrame(arr,columns=["a","b","c"])

In [34]:
data1

    a   b   c
0  13  14  18
1  10  17  19
2  19  19  16

In [41]:
data.describe

<bound method NDFrame.describe of        Name Product Name  Sale Price    MRP  Rating   Sale Date
0     Alice     Product1      100.00 120.00    4.50  01-08-2023
1       Bob     Product2      150.00 170.00    4.00  02-08-2023
2   Charlie          NaN      200.00    NaN    3.50  03-08-2023
3     David     Product4         NaN 210.00    5.00  04-08-2023
4       Eva     Product5      250.00 270.00     NaN  05-08-2023
5     Frank          NaN      300.00 320.00    4.70         NaN
6     Grace     Product7      350.00    NaN    4.10  07-08-2023
7     Helen     Product8         NaN 370.00    3.80  08-08-2023
8       Ivy     Product9      400.00 420.00     NaN         NaN
9      Jack          NaN      450.00    NaN    4.30  10-08-2023
10     Kara    Product11      500.00 520.00    4.90  11-08-2023
11      Leo    Product12         NaN 570.00     NaN         NaN
12     Mona    Product13      550.00    NaN    3.90  13-08-2023
13     Nina    Product14      600.00 620.00    4.60  14-08-2023
14    Oscar          NaN      650.00 670.00    4.20  15-08-2023>

In [40]:
data.describe()

       Sale Price    MRP  Rating
count       12.00  11.00   12.00
mean       375.00 387.27    4.29
std        180.28 188.37    0.46
min        100.00 120.00    3.50
25%        237.50 240.00    3.98
50%        375.00 370.00    4.25
75%        512.50 545.00    4.62
max        650.00 670.00    5.00

In [42]:
data.describe().T

            count   mean    std    min    25%    50%    75%    max
Sale Price  12.00 375.00 180.28 100.00 237.50 375.00 512.50 650.00
MRP         11.00 387.27 188.37 120.00 240.00 370.00 545.00 670.00
Rating      12.00   4.29   0.46   3.50   3.98   4.25   4.62   5.00

In [43]:
data.dtypes

Name             object
Product Name     object
Sale Price      float64
MRP             float64
Rating          float64
Sale Date        object
dtype: object

In [44]:
data.columns

Index(['Name', 'Product Name', 'Sale Price', 'MRP', 'Rating', 'Sale Date'], dtype='object')

In [47]:
#check missing values
data.isna()

     Name  Product Name  Sale Price    MRP  Rating  Sale Date
0   False         False       False  False   False      False
1   False         False       False  False   False      False
2   False          True       False   True   False      False
3   False         False        True  False   False      False
4   False         False       False  False    True      False
5   False          True       False  False   False       True
6   False         False       False   True   False      False
7   False         False        True  False   False      False
8   False         False       False  False    True       True
9   False          True       False   True   False      False
10  False         False       False  False   False      False
11  False         False        True  False    True       True
12  False         False       False   True   False      False
13  False         False       False  False   False      False
14  False          True       False  False   False      False

In [57]:
data.isna().sum()

Name            0
Product Name    4
Sale Price      3
MRP             4
Rating          3
Sale Date       3
dtype: int64

In [55]:
if "Name" in data.columns:
  print("yes")

yes

In [5]:
#data.dropna(axis=0)
data.dropna(inplace=True)

In [11]:
data.dropna(axis=0)

     Name Product Name  Sale Price    MRP  Rating   Sale Date
0   Alice     Product1      100.00 120.00    4.50  01-08-2023
1     Bob     Product2      150.00 170.00    4.00  02-08-2023
10   Kara    Product11      500.00 520.00    4.90  11-08-2023
13   Nina    Product14      600.00 620.00    4.60  14-08-2023

In [7]:
data

     Name Product Name  Sale Price    MRP  Rating   Sale Date
0   Alice     Product1      100.00 120.00    4.50  01-08-2023
1     Bob     Product2      150.00 170.00    4.00  02-08-2023
10   Kara    Product11      500.00 520.00    4.90  11-08-2023
13   Nina    Product14      600.00 620.00    4.60  14-08-2023